### ISSUE TITLE
메인페이지, 마이페이지 관련 Navigation Issue

### ISSUE THREAD

**Issue by dooking** [TEAM-BIDI/bidi#12]
## 💁 목표
- 메인페이지와 마이페이지는 어느 tab에도 속하지 않음
- bottom tab에 속하지 않은 상태를 구현해야함

## 📑 체크리스트
- [ ] 화면 왼쪽 상단에 있는 로고를 클릭 시, 메인페이지로 이동
- [x] 화면 오른쪽 상단에 있는 아이콘을 클릭 시, 마이페이지로 이동

**Comment by dooking** [comment]
ㅇㅇㅇㅇㅇ

**Comment by longshiine** [comment]
https://reactnavigation.org/docs/hiding-tabbar-in-screens/
