### ISSUE TITLE
Navbar 재구성

### ISSUE THREAD

**Issue by dooking** [TEAM-BIDI/bidi#16]
## 💁 목표
- 디자인에 맞춰 Navbar 재구성
- Header, bottom 재구성
<img width="300" alt="스크린샷 2021-07-19 오후 2 15 51" src="https://user-images.githubusercontent.com/60457112/126106579-d08fef45-ced6-4ef0-b2fd-237deaeb1087.png">

## 📑 체크리스트
- [x] Header : 좌측상단에 로고, 우측상단에 알림 아이콘 + DM 아이콘
- [x] Bottom tab : 5개의 tab 생성

**Comment by dooking** [comment]
@longshiine DM 뱃지를 어케 구현할지 고민해봐야 할듯!?

**Comment by longshiine** [comment]
DM 뱃지는 작은 view하나를 absolute로 올리면 깨지려나
혹은 우리도 sementic ui같은 스타일 관련 라이브러리 하나 가져오는게 나을듯?
